apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  namespace: devops-monitor
spec:
  containers:
    - args:
        - sleep
        - '1000000'
      image: busybox
      name: busybox
